### ISSUE TITLE
Merge from latest official repo (mostly to fix Node 16 deprecation)

### ISSUE THREAD

**Issue by Piedone** [BuildJet/cache#1]
Please update this repo from the official one. This is most important because that [was upgraded to Node 20](https://github.com/actions/cache/commit/2001ca4114dbc44888c30c0ec3550fecf724b8d9), while v16 used by this action is deprecated.

**Comment by alexbjorlig** [comment]
Should we use `buildjet/cache@v3` or `buildjet/cache@v4` to get rid of the warning?

**Comment by Piedone** [comment]
There's no v4 yet and the latest source still uses Node.js v16, so you can't get rid of the warning.

**Comment by karfau** [comment]
v4 has been released

**Comment by Piedone** [comment]
I think this can be closed, then @thinkafterbefore?

**Comment by thinkafterbefore** [comment]
Yeah, that's right! I just published the v4, so now both v3 and v4 are supported. Thanks for bringing this to our attention!

**Comment by Piedone** [comment]
Great, thanks!
